In [1]:
!pip install selenium

Requirement already satisfied: selenium in c:\users\admin\anaconda3\lib\site-packages (4.9.1)
Requirement already satisfied: trio~=0.17 in c:\users\admin\anaconda3\lib\site-packages (from selenium) (0.22.0)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\admin\anaconda3\lib\site-packages (from selenium) (0.10.2)
Requirement already satisfied: urllib3[socks]<3,>=1.26 in c:\users\admin\anaconda3\lib\site-packages (from selenium) (1.26.11)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\admin\anaconda3\lib\site-packages (from selenium) (2022.9.14)
Requirement already satisfied: cffi>=1.14 in c:\users\admin\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.1)
Requirement already satisfied: sniffio in c:\users\admin\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: outcome in c:\users\admin\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: attrs>=19.2.0 in c:\users\admin\anaconda3\lib\site-packages (from trio~=0.17->selenium) (21.4.0)
Requirement already satisfied: exceptiongroup>=1.0.0rc9 in c:\users\admin\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.1.1)
Requirement already satisfied: idna in c:\users\admin\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.3)
Requirement already satisfied: sortedcontainers in c:\users\admin\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: async-generator>=1.9 in c:\users\admin\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.10)
Requirement already satisfied: wsproto>=0.14 in c:\users\admin\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\users\admin\anaconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\users\admin\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\admin\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

In [2]:
from selenium import webdriver
from selenium.webdriver.common.by import By
import pandas as pd

In [3]:
start_date = pd.to_datetime('2023-06-01')
end_date = pd.to_datetime('2023-08-31')

data = []

for date in pd.date_range(start_date, end_date, freq='D'):
    search_url = f"https://m-flight.naver.com/flights/international/ICN-PAR-{date.strftime('%Y%m%d')}?adult=1&fareType=P"

    browser = webdriver.Chrome('C:/Users/chromedriver.exe')
    browser.get(search_url)
    browser.implicitly_wait(20)

    oneday = browser.find_elements(By.CLASS_NAME, "indivisual_inner__2RKYG")
    for i in range(len(oneday)):
        rr1 = oneday[i].find_element(By.CLASS_NAME, "indivisual_schedule__1tq7j").text
        rr2 = oneday[i].find_element(By.CLASS_NAME, "item_ItemPriceList__22YBo").text
        data.append([date, rr1, rr2])

    browser.quit()

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_27304\3035335945.py:9: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  browser = webdriver.Chrome('C:/Users/chromedriver.exe')

In [4]:
df = pd.DataFrame(data, columns=['date', 'rr1', 'rr2'])

In [5]:
df

,date,rr1,rr2
0,2023-06-01,"폴란드항공\n11:20ICN\n09:55CDG\n+1일\n경유 1, 29시간 35분","성인/롯데카드\n편도 1,686,300원~"
1,2023-06-01,"폴란드항공\n11:20ICN\n18:55CDG\n+1일\n경유 1, 38시간 35분","성인/롯데카드\n편도 1,686,300원~"
2,2023-06-01,"여러항공사\n08:20ICN\n19:25CDG\n경유 1, 18시간 05분","성인/롯데카드\n편도 1,842,900원~"
3,2023-06-01,"루프트한자\n11:40ICN\n23:25CDG\n경유 1, 18시간 45분","성인/롯데카드\n편도 1,878,100원~"
4,2023-06-01,"루프트한자\n12:20ICN\n22:55CDG\n경유 1, 17시간 35분","성인/롯데카드\n편도 1,889,800원~"
...,...,...,...
2458,2023-08-31,"폴란드항공\n11:20ICN\n09:55CDG\n+1일\n경유 1, 29시간 35분","성인/현대 M2/M3 Edition2(이용실적 충족시)\n편도 2,366,600원~"
2459,2023-08-31,"폴란드항공\n11:20ICN\n18:55CDG\n+1일\n경유 1, 38시간 35분","성인/현대 M2/M3 Edition2(이용실적 충족시)\n편도 2,366,600원~"
2460,2023-08-31,"여러항공사\n11:50ICN\n12:30CDG\n+1일\n경유 1, 31시간 40분","성인/모든 결제수단\n편도 2,451,300원~"
2461,2023-08-31,"여러항공사\n11:50ICN\n23:40CDG\n경유 1, 18시간 50분","성인/모든 결제수단\n편도 2,451,300원~"
2462,2023-08-31,"여러항공사\n11:50ICN\n10:50CDG\n+1일\n경유 1, 30시간 00분","성인/모든 결제수단\n편도 2,451,300원~"

In [6]:
split0 = df[['date']]

In [7]:
split0.columns = ['Date']

In [8]:
split1 = df.rr1.str.split('\n', expand = True)
split1.columns = ['Airline', 'Departure', 'Arrival', 'Day', 'time']

In [9]:
split01 = pd.concat([split0, split1], axis = 1)

In [11]:
split2 = df.rr2.str.split('\n', expand = True)
split2.columns = ['Payment', 'Price']

In [12]:
split012 = pd.concat([split01, split2], axis = 1)

In [13]:
split012

,Date,Airline,Departure,Arrival,Day,time,Payment,Price
0,2023-06-01,폴란드항공,11:20ICN,09:55CDG,+1일,"경유 1, 29시간 35분",성인/롯데카드,"편도 1,686,300원~"
1,2023-06-01,폴란드항공,11:20ICN,18:55CDG,+1일,"경유 1, 38시간 35분",성인/롯데카드,"편도 1,686,300원~"
2,2023-06-01,여러항공사,08:20ICN,19:25CDG,"경유 1, 18시간 05분",None,성인/롯데카드,"편도 1,842,900원~"
3,2023-06-01,루프트한자,11:40ICN,23:25CDG,"경유 1, 18시간 45분",None,성인/롯데카드,"편도 1,878,100원~"
4,2023-06-01,루프트한자,12:20ICN,22:55CDG,"경유 1, 17시간 35분",None,성인/롯데카드,"편도 1,889,800원~"
...,...,...,...,...,...,...,...,...
2458,2023-08-31,폴란드항공,11:20ICN,09:55CDG,+1일,"경유 1, 29시간 35분",성인/현대 M2/M3 Edition2(이용실적 충족시),"편도 2,366,600원~"
2459,2023-08-31,폴란드항공,11:20ICN,18:55CDG,+1일,"경유 1, 38시간 35분",성인/현대 M2/M3 Edition2(이용실적 충족시),"편도 2,366,600원~"
2460,2023-08-31,여러항공사,11:50ICN,12:30CDG,+1일,"경유 1, 31시간 40분",성인/모든 결제수단,"편도 2,451,300원~"
2461,2023-08-31,여러항공사,11:50ICN,23:40CDG,"경유 1, 18시간 50분",None,성인/모든 결제수단,"편도 2,451,300원~"
2462,2023-08-31,여러항공사,11:50ICN,10:50CDG,+1일,"경유 1, 30시간 00분",성인/모든 결제수단,"편도 2,451,300원~"

In [14]:
split012.to_csv('airpar_pn.csv', index=False)