In [1]:
!pip install selenium

Requirement already satisfied: selenium in c:\users\admin\anaconda3\lib\site-packages (4.9.1)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\admin\anaconda3\lib\site-packages (from selenium) (0.10.2)
Requirement already satisfied: urllib3[socks]<3,>=1.26 in c:\users\admin\anaconda3\lib\site-packages (from selenium) (1.26.11)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\admin\anaconda3\lib\site-packages (from selenium) (2022.9.14)
Requirement already satisfied: trio~=0.17 in c:\users\admin\anaconda3\lib\site-packages (from selenium) (0.22.0)
Requirement already satisfied: cffi>=1.14 in c:\users\admin\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.1)
Requirement already satisfied: idna in c:\users\admin\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.3)
Requirement already satisfied: attrs>=19.2.0 in c:\users\admin\anaconda3\lib\site-packages (from trio~=0.17->selenium) (21.4.0)
Requirement already satisfied: sortedcontainers in c:\users\admin\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: outcome in c:\users\admin\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: exceptiongroup>=1.0.0rc9 in c:\users\admin\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.1.1)
Requirement already satisfied: sniffio in c:\users\admin\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: async-generator>=1.9 in c:\users\admin\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.10)
Requirement already satisfied: wsproto>=0.14 in c:\users\admin\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\users\admin\anaconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\users\admin\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\admin\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

In [2]:
from selenium import webdriver
from selenium.webdriver.common.by import By
import pandas as pd

In [3]:
start_date = pd.to_datetime('2023-06-01')
end_date = pd.to_datetime('2023-08-31')

data = []

for date in pd.date_range(start_date, end_date, freq='D'):
    search_url = f"https://m-flight.naver.com/flights/international/PAR-SEL-{date.strftime('%Y%m%d')}?adult=1&fareType=P"

    browser = webdriver.Chrome('C:/Users/chromedriver.exe')
    browser.get(search_url)
    browser.implicitly_wait(20)

    oneday = browser.find_elements(By.CLASS_NAME, "indivisual_inner__2RKYG")
    for i in range(len(oneday)):
        rr1 = oneday[i].find_element(By.CLASS_NAME, "indivisual_schedule__1tq7j").text
        rr2 = oneday[i].find_element(By.CLASS_NAME, "item_ItemPriceList__22YBo").text
        data.append([date, rr1, rr2])

    browser.quit()

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_30204\3611842190.py:9: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  browser = webdriver.Chrome('C:/Users/chromedriver.exe')

In [4]:
df = pd.DataFrame(data, columns=['date', 'rr1', 'rr2'])

In [5]:
df

,date,rr1,rr2
0,2023-06-01,싱가포르항공스쿠트항공 공동운항\n22:40CDG\n10:50ICN\n+2일\n경유 ...,"성인/KB국민카드\n편도 2,650,400원~"
1,2023-06-01,"캐세이퍼시픽항공\n12:45CDG\n12:35ICN\n+1일\n경유 1, 16시간 50분","성인/KB국민카드\n편도 2,729,300원~"
2,2023-06-01,"캐세이퍼시픽항공\n12:45CDG\n19:15ICN\n+1일\n경유 1, 23시간 30분","성인/KB국민카드\n편도 2,729,300원~"
3,2023-06-01,"캐세이퍼시픽항공\n12:45CDG\n21:15ICN\n+1일\n경유 1, 25시간 30분","성인/KB국민카드\n편도 2,729,300원~"
4,2023-06-01,"에어프랑스\n11:50CDG\n07:05ICN\n+1일\n직항, 12시간 15분","성인/KB국민카드\n편도 2,964,100원~"
...,...,...,...
9728,2023-08-31,"유나이티드항공\n17:00CDG\n14:45ICN\n+2일\n경유 2, 38시간 45분","성인/모든 결제수단\n편도 8,803,000원~"
9729,2023-08-31,"유나이티드항공\n12:25CDG\n14:45ICN\n+2일\n경유 2, 43시간 20분","성인/모든 결제수단\n편도 8,803,000원~"
9730,2023-08-31,"유나이티드항공\n17:00CDG\n14:45ICN\n+2일\n경유 2, 38시간 45분","성인/모든 결제수단\n편도 8,803,000원~"
9731,2023-08-31,"유나이티드항공\n09:45CDG\n14:45ICN\n+2일\n경유 2, 46시간 00분","성인/모든 결제수단\n편도 8,803,000원~"
9732,2023-08-31,"유나이티드항공\n11:15CDG\n14:45ICN\n+2일\n경유 2, 44시간 30분","성인/모든 결제수단\n편도 8,810,600원~"

In [6]:
split0 = df[['date']]

In [7]:
split0.columns = ['Date']

In [8]:
split1 = df.rr1.str.split('\n', expand = True)
split1.columns = ['Airline', 'Departure', 'Arrival', 'Day', 'time']

In [9]:
split01 = pd.concat([split0, split1], axis = 1)

In [10]:
split2 = df.rr2.str.split('\n', expand = True)
split2.columns = ['Payment', 'Price']

In [11]:
split012 = pd.concat([split01, split2], axis = 1)

In [12]:
split012

,Date,Airline,Departure,Arrival,Day,time,Payment,Price
0,2023-06-01,싱가포르항공스쿠트항공 공동운항,22:40CDG,10:50ICN,+2일,"경유 1, 29시간 10분",성인/KB국민카드,"편도 2,650,400원~"
1,2023-06-01,캐세이퍼시픽항공,12:45CDG,12:35ICN,+1일,"경유 1, 16시간 50분",성인/KB국민카드,"편도 2,729,300원~"
2,2023-06-01,캐세이퍼시픽항공,12:45CDG,19:15ICN,+1일,"경유 1, 23시간 30분",성인/KB국민카드,"편도 2,729,300원~"
3,2023-06-01,캐세이퍼시픽항공,12:45CDG,21:15ICN,+1일,"경유 1, 25시간 30분",성인/KB국민카드,"편도 2,729,300원~"
4,2023-06-01,에어프랑스,11:50CDG,07:05ICN,+1일,"직항, 12시간 15분",성인/KB국민카드,"편도 2,964,100원~"
...,...,...,...,...,...,...,...,...
9728,2023-08-31,유나이티드항공,17:00CDG,14:45ICN,+2일,"경유 2, 38시간 45분",성인/모든 결제수단,"편도 8,803,000원~"
9729,2023-08-31,유나이티드항공,12:25CDG,14:45ICN,+2일,"경유 2, 43시간 20분",성인/모든 결제수단,"편도 8,803,000원~"
9730,2023-08-31,유나이티드항공,17:00CDG,14:45ICN,+2일,"경유 2, 38시간 45분",성인/모든 결제수단,"편도 8,803,000원~"
9731,2023-08-31,유나이티드항공,09:45CDG,14:45ICN,+2일,"경유 2, 46시간 00분",성인/모든 결제수단,"편도 8,803,000원~"
9732,2023-08-31,유나이티드항공,11:15CDG,14:45ICN,+2일,"경유 2, 44시간 30분",성인/모든 결제수단,"편도 8,810,600원~"

In [13]:
split012.to_csv('airkor_pn.csv', index=False)